new/nokstech2/Models/ErrorViewModel.cs
namespace nokstech2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

new/nokstech2/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using nokstech2.Models;
using System.Diagnostics;

namespace nokstech2.Controllers
{
    public class ContactController : Controller
    {
        private readonly ILogger<ContactController> _logger;

        public ContactController(ILogger<ContactController> logger)
        {
            _logger = logger;
        }

        public IActionResult Contact()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

new/nokstech2/Controllers/DownloadPageController.cs
using Microsoft.AspNetCore.Mvc;
using nokstech2.Models;
using System.Diagnostics;

namespace nokstech2.Controllers
{
    public class DownloadPageController : Controller
    {
        private readonly ILogger<DownloadPageController> _logger;

        public DownloadPageController(ILogger<DownloadPageController> logger)
        {
            _logger = logger;
        }

        public IActionResult Downloadpage()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

new/nokstech2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using nokstech2.Models;
using System.Diagnostics;

namespace nokstech2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Default()
        {
            return View();
        }

        public IActionResult Policy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

new/nokstech2/Controllers/PricingController.cs
using Microsoft.AspNetCore.Mvc;
using nokstech2.Models;
using System.Diagnostics;

namespace nokstech2.Controllers
{
    public class PricingController : Controller
    {
        private readonly ILogger<PricingController> _logger;

        public PricingController(ILogger<PricingController> logger)
        {
            _logger = logger;
        }

        public IActionResult Pricing()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

new/nokstech2/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using nokstech2.Models;
using System.Diagnostics;

namespace nokstech2.Controllers
{
    public class RegisterController : Controller
    {
        private readonly ILogger<RegisterController> _logger;

        public RegisterController(ILogger<RegisterController> logger)
        {
            _logger = logger;
        }

        public IActionResult Register()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

new/nokstech2/Views/Contact/contact.cshtml
@{
    ViewData["Title"] = "Contact Us";
    ViewData["Css"] = "contact.css";
}

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
     <meta  name="viewport" content="width=device-width, initial-scale=1.0>" />
    <!--<link href="contact.css" rel="stylesheet" />-->
    <title>contact</title>
</head>
<body>
    <form id="form1" runat="server">
    <div class="maindiv">
       <div class="mainbar">
               
             
               <div class="content">
                   <img class="image" src="images/call(1).png" />
                    <div class="phonenumber">07081721031</div>
               </div>

             <div class="content1">
                 <img class="image" src="images/picture2.png" />
                 <div class="gmail">premiumdataflex@gmail.com</div>
             </div>
            
  
             <div class="text">Back office</div>


             <div class="contentdiv">
                 <img class="image" src="images/exit.png" />
                <a class="edit" href="http://noksworld-003-site22.btempurl.com/" target="_blank" rel="noopener noreferrer">Sign in</a>
             </div>
                
             <div class="contentdiv">
                 <img class="image" src="images/sign-up.png" />
                 <a class="edit" href="http://noksworld-003-site22.btempurl.com/" target="_blank" rel="noopener noreferrer">Sign up</a>
             </div>
             </div>

           
                

         </div>
           

             <div class="topbar">
                 <div class="logo">
                     <img class="img" src="images/logomain4.0.png" />
                     <div class="newtext">NOKS</div>
                     <div class="newtext1">POS</div>
                 </div>
                 <div class="housing">
                <a class="edit1" asp-area="" asp-controller="Home" asp-action="">HOME</a>
                <a class="edit2" asp-area="" asp-controller="Contact" asp-action="Contact">CONTACT US</a>
                <a class="edit2" asp-area="" asp-controller="Pricing" asp-action="Pricing">PRICING</a>
                <a class="edit2" asp-area="" asp-controller="Pricing" asp-action="Pricing">FEATURES</a>
                <a class="edit2" asp-area="" asp-controller="Pricing" asp-action="Pricing">HELP</a>
                <a class="edit2" asp-area="" asp-controller="Register" asp-action="Register">GET STARTED</a>

                       </div>
              
             </div>

         <div class="div">
             <div class="div1">Contact us</div>
             <div class="div2">Have any question or want to reach us, We’d love to hear from you.</div>
    </div>

        <div class="divbox">
            <div class="divbox1">
                <div class="divbox1a">Office Address</div>
                <div class="divbox1b">9, Vanni Street, Morgan Estate, <br />Ojodu-Berger, Lagos state</div>
            </div>

             <hr class="new1">


<div class="divbox1a">Contact Info</div>
        <div class="divbox1c">Phone: +2347081721031</div>
        <div class="divbox1c">Email: premiumdataflex@gmail.com</div>

        </div>

         <div class="boxhouse">
            
               <div class="boxone">Copyright © 2024 NoksPos</div>
           <a href="Policy.html"><div class="policy">privacy policy</div></a>
               
                 </div>

    </div>
    </form>
</body>
</html>

new/nokstech2/Views/DownloadPage/downloadpage.cshtml
@{
    ViewData["Title"] = "downloadpage";
    ViewData["Css"] = "downloadpage.css";
    ViewData["Extra_Css"] = "StyleSheet.css";
}

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <!--link href="downloadpage.css" rel="stylesheet" />-->
    <!--<link href="StyleSheet.css" rel="stylesheet" />-->
</head>
<body>
    <form id="form1" runat="server">
    <div>
 
       <div class="mainbar">
               
             
               <div class="content">
                   <img class="image" src="images/call(1).png" />
                    <div class="phonenumber">07081721031</div>
               </div>

             <div class="content1">
                 <img class="image" src="images/picture2.png" />
                 <div class="gmail">premiumdataflex@gmail.com</div>
             </div>
            
  
         
                <a class="text" asp-area="" asp-controller="DownloadPage" asp-action="DownloadPage">Download</a>

             <div class="contentdiv">
                 <img class="image" src="images/exit.png" />
                 <a class="edit" href="http://noksworld-003-site22.btempurl.com/" target="_blank" rel="noopener noreferrer">Sign in</a>
             </div>
                
             <div class="contentdiv">
                 <img class="image" src="images/sign-up.png" />
                 <a class="edit" href="http://noksworld-003-site22.btempurl.com/" target="_blank" rel="noopener noreferrer">Sign up</a>
             </div>

             
                

         </div>  

            <div class="topbar">
                 <div class="logo">
                     <img class="img" src="images/logomain4.0.png" />
                     <div class="newtext">NOKS</div>
                     <div class="newtext1">POS</div>
                 </div>
                 <div class="housing">
                    <a class="edit1" asp-area="" asp-controller="Home" asp-action="">HOME</a>
                    <a class="edit2" asp-area="" asp-controller="Contact" asp-action="Contact">CONTACT US</a>
                    <a class="edit2" asp-area="" asp-controller="Pricing" asp-action="Pricing">PRICING</a>
                    <a class="edit2" asp-area="" asp-controller="Pricing" asp-action="Pricing">FEATURES</a>
                    <a class="edit2" asp-area="" asp-controller="Pricing" asp-action="Pricing">HELP</a>
                    <a class="edit2" asp-area="" asp-controller="Register" asp-action="Register">GET STARTED</a>

                </div>
             </div>

        <div class="block1">
            <div class="blocktext">DOWNLOAD THIS APP</div>
              <div class="blocktext1">Welcome to the future of productivity and convenience! "Download This App" is your gateway to streamlining your daily activities, optimizing your time, and enhancing your overall efficiency.</div>
            <div class="blocktext2"></div>
        </div>
        <div class="block1">
            <div class="block2">
                <img class="blockimg" src="images/hand1.png" /></div>

        </div>
         <ol>
        <li>1. <a href="https://www.nokstech.com/sql%20management.zip">Sql Management</a></li>
        <li>2.  <a href="https://www.nokstech.com/SQLEXPR_x64_ENU.zip">Sql Server</a></li>
        <li>3.<a href="https://www.nokstech.com/CR13SP33MSI64_0-80007712.zip">Crystal Report</a></li>
        <li>4.<a href="https://www.nokstech.com/CDRIVEFOLDER.zip">Cdrivefolder</a></li>
        <li>5. <a href="https://www.nokstech.com/XPrinter Driver V8.0.exe">Printer Driver</a></li>
        <li>6. <a href="https://www.nokstech.com/cra.zip">Desktop Software</a></li>
        <li>7. <a href="https://www.nokstech.com/script.zip">Script</a></li>
        <li>8. <a href="https://www.nokstech.com/file_upload_LA24.0.zip">FileUpload</a></li>
    </ol>
    </div>
    </form>
</body>
</html>

new/nokstech2/Views/Home/Index1.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

new/nokstech2/Views/Home/default.cshtml
@{
    ViewData["Title"] = "nokspos";
    ViewData["Css"] = null;
}

<!DOCTYPE html>


<head runat="server">
    <meta  name="viewport" content="width=device-width, initial-scale=1.0>" />
    <!--<link href="StyleSheet.css" rel="stylesheet" />-->
   
     
      <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    
    <script src="noks.js"></script>
      <title>nokspos</title>
     <link rel="icon" type="image/x-icon" href="/images/favicon.ico"/>


  
</head>
<body>
    <form id="form1" runat="server">
       <div class="maindiv">
           <div class="mainbar">
               
             
               <div class="content">
                   <img class="image" src="images/call(1).png" />
                    <div class="phonenumber">07081721031</div>
               </div>

             <div class="content1">
                 <img class="image" src="images/picture2.png" />
                 <div class="gmail">premiumdataflex@gmail.com</div>
             </div>



                <a class="text" asp-area="" asp-controller="DownloadPage" asp-action="DownloadPage">Download</a>

             <div class="contentdiv">
                 <img class="image" src="images/exit.png" />
                 <a class="edit" href="http://noksworld-003-site22.btempurl.com/" target="_blank" rel="noopener noreferrer">Sign in</a>
             </div>
                
             <div class="contentdiv">
                 <img class="image" src="images/sign-up.png" />
                 <a class="edit" href="http://noksworld-003-site22.btempurl.com/" target="_blank" rel="noopener noreferrer">Sign up</a>
             </div>

             
                

         </div>
           

             <div class="topbar">
                 <div class="logo">
                     <img class="img" src="images/logomain4.0.png" />
                     <div class="newtext">NOKS</div>
                     <div class="newtext1">POS</div>
                 </div>
                 <div class="housing">
                    <a class="edit1" asp-area="" asp-controller="Home" asp-action="">HOME</a>
                    <a class="edit2" asp-area="" asp-controller="Contact" asp-action="Contact">CONTACT US</a>
                    <a class="edit2" asp-area="" asp-controller="Pricing" asp-action="Pricing">PRICING</a>
                    <a class="edit2" asp-area="" asp-controller="Pricing" asp-action="Pricing">FEATURES</a>
                    <a class="edit2" asp-area="" asp-controller="Pricing" asp-action="Pricing">HELP</a>
                    <a class="edit2" asp-area="" asp-controller="Register" asp-action="Register">GET STARTED</a>
                 </div>
             </div>


           <div class="housediv">
                
                     <div class="firstdiv">
                         <img class="photo" src="images/image1.png" /></div>
     
             
   </div>

            <div class="divbox">
                  <div class="divbox1">
                     <div class="divtext">TRENDING OFFERS</div>
                     
                  </div>
                  <div class="mainbox">
                       <div class="divtext1B">
                           
                          <div class="ios">
                               <img class="iosimage" src="images/Untitled%20design.png" /> </div>
                           <div class="ios1">IOS AND ANDROID APP</div>
                    <div class="iostext">Transform your business with our IOS mobile point-of-sale app and Andriod mobile point-of-sale app!Enjoy secured payments, manage inventory effortlessly and the flexibility to run your business from the palm of your hand </div>
                         
                           </div>


                   
                  <div class="divtext1D">
                      <div class="web">
                          <img class="webimage" src="images/Untitled%20design(2).png" /> </div>
                      <div class="web1">WEBSITE SOFTWARE</div>
                      <div class="webtext">Empower your business with our web-based mobile point-of-sale app! Enjoy the convience of a cloud-based solution, ensuring accessibility and flexibity for your business needs anywhere around the world</div>
                  </div>
                   
                      
                      
                      
                       <div class="divtext1E">
                           <div class="desktop">
                               <img class="desktopimage" src="images/0005.png" /> </div>

                           <div class="desktop1">DESKTOP SOFTWARE</div>
                        <div class="desktoptext">Optimize your sales-based mobile point-of-sale app!This robust app provides secure payment processing, detailed sales analytics and the flexibity to run your business easy from your desktop</div>
                    </div>
                  </div>
                  
                   
              </div>


<div class="housedivone">
            <div class="firstdivone">
                <img class="picture2" src="images/image2.jpg" /></div>
            <div class="seconddivone">
                <div class="thirddiv4">Mobile Point of Sale Software</div>
                 <div class="thirddiv5">
                     Transform your smartphone or tablet into a complete Point of Sale<br/> system. Manage sales, inventory, and your employees seamlessly.<br/> Setup multiple outlets even in different business types and manage<br/> them online from anywhere. </div>
               <ol>
        <li>1. Manage sales seamlessly </li>
        <li>2. Inventory management</li>
        <li>3. Manage shops</li>
        <li>4. Manage teams and employee performance</li>
        <li>5. Customer loyalty </li>
        <li>6. Reporting and analytics</li>
    </ol>
                 
            </div>
        </div>
   
              <div class="housedivtwo">
       
            <div class="firstdivtwo">
                <div class="thirddiv10">Manage your sales seamlessly</div>
               <ol>
    <li>1.Sell from a smartphone or tablet </li>
    <li>2.Save and manage pending bills (Hold Bill)</li>
    <li>3.Keep recording sales even when offline</li>
    <li>4.Issue printed or share electronic receipts </li>
    <li>5.Connect a receipt printer/barcode scanner  </li>
    <li>6.Dashboard app to monitor real-time sales & stock </li>
</ol>

 


        </div>


        <div class="seconddivtwo">
            <img class="picture4" src="images/Comp1.jpg" /></div>
    </div>
        
 <div class="housedivthree">
        <div class="firstdivthree">
            <img class="picture3" src="images/PNG 2.png" />
        </div>
        <div class="seconddivthree">
<div class="thirddiv8">Inventory management </div>
            <div class="thirddiv9">(standalone and centralized)</div>

                           <ol>
    <li>1.Centralized inventory to manage stocks in multiple shops and businesses </li>
    <li>2.Realtime tracking of stocks</li>
    <li>3.Automated low stock and stock expiry alerts</li>
    <li> 4.Send automated email orders to suppliers track receipts through </li>
    <li>5.Transfer goods between stores  </li>
    <li>6.Cover complete process of goods ordering to goods receiving </li>
     </ol>

            
        </div>
    </div>
<div class="housedivfour">
             <div class="firstdivfour">
                 <div class="thirddiv7">Manage your shop(s) </div>
                                        <ol>
<li>1.Expand your business by adding new shops </li>
<li>2.Manage sales, stocks, employees and customers in the same or different businesses</li>
<li>3.Filter all the reports and analytics in shop wise</li>
<li> 4.Create users for different shops and grant accesses </li>
<li>5.Setup different receipts design and other settings in shop wise</li>
<li>6.Manage all shops from online </li>
 </ol>

                  


             </div>
             <div class="seconddivfour">
                 <img class="picture3" src="images/PNG.png" /> </div>
        </div>

<div class="housedivfive">
    <div class="firstdivfive">
        <img class="picture3" src="images/PNG 3.png" /></div>
    <div class="seconddivfive">
        <div class="thirddiv10A">Reporting and Analytics</div>
                                                                   <ol>
<li>1.Dashboard with key data and filtrations </li>
<li>2.View revenue and profit for each shop and all shops  </li>
<li>3.Identify top selling products</li>
<li>4.Track sales trends to plan sales and logistics</li>
<li>5.View entire sales history </li>
<li>6.Export all reports to spreadsheets enabling further analysis </li>
 </ol>

           

    </div>
</div>
           
           
           
           <div class="boxhouse">
            
               <div class="boxone">Copyright © 2024 NoksPos</div>
                <a asp-area="" asp-controller="Home" asp-action="Policy"><div class="policy">privacy policy</div></a>
               
                 </div>

         

          










      </div>
    </form>
</body>
</html>

new/nokstech2/Views/Pricing/pricing.cshtml
@{
    ViewData["Title"] = "Pricing";
    ViewData["Css"] = "pricing.css";
}

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta  name="viewport" content="width=device-width, initial-scale=1.0>" />
    <!--<link href="pricing.css" rel="stylesheet" />
    <title>pricing</title>-->
</head>
<body>
    <form id="form1" runat="server">
    <div class="maindiv">
           <div class="mainbar">
               
             
               <div class="content">
                   <img class="image" src="images/call(1).png" />
                    <div class="phonenumber">07081721031</div>
               </div>

             <div class="content1">
                 <img class="image" src="images/picture2.png" />
                 <div class="gmail">premiumdataflex@gmail.com</div>
             </div>
            
  
             <div class="text">Back office</div>


             <div class="contentdiv">
                 <img class="image" src="images/exit.png" />
                  <a class="edit" href="http://noksworld-003-site22.btempurl.com/" target="_blank" rel="noopener noreferrer">Sign in</a>
             </div>
                
             <div class="contentdiv">
                 <img class="image" src="images/sign-up.png" />
                  <a class="edit" href="http://noksworld-003-site22.btempurl.com/" target="_blank" rel="noopener noreferrer">Sign up</a>
             </div>

            
                

         </div>
           

             <div class="topbar">
                 <div class="logo">
                     <img class="img" src="images/logomain4.0.png" />
                     <div class="newtext">NOKS</div>
                     <div class="newtext1">POS</div>
                 </div>
                 <div class="housing">
                    <a class="edit1" asp-area="" asp-controller="Home" asp-action="">HOME</a>
                    <a class="edit2" asp-area="" asp-controller="Contact" asp-action="Contact">CONTACT US</a>
                    <a class="edit2" asp-area="" asp-controller="Pricing" asp-action="Pricing">PRICING</a>
                    <a class="edit2" asp-area="" asp-controller="Pricing" asp-action="Pricing">FEATURES</a>
                    <a class="edit2" asp-area="" asp-controller="Pricing" asp-action="Pricing">HELP</a>
                    <a class="edit2" asp-area="" asp-controller="Register" asp-action="Register">GET STARTED</a>

                </div>
             </div>

         <div class="div">
             <div class="div1">Pricing Plans</div>
             <div class="div2">Choose your pricing plan</div>
    </div>

        <div class="divbox">
            <div class="divbox1">
               <div class="divboxmain">
                 <div class="divbox1a">
                     <img class="photo" src="images/mission.png" /></div>
                <div class="divbox1b">STANDARD</div>
                <div class="divbox1c">₦60,000</div>
                <div class="divbox1ci">/year</div>
                
          </div>
                <hr class="new1">

                <div class="divbox1d">2 users</div>
                 <div class="divbox1d">1 business locations</div>
                 <div class="divbox1d">point of sales</div>
                 <div class="divbox1d">Inventory Manager</div>
                 <div class="divbox1d">Billing and invoicing</div>
                 <div class="divbox1d">Marketing and CRM</div>
                 <div class="divbox1d">Payments solutions </div>
                 <div class="divbox1d">Customer Settings</div>
                <div class="divbox1e">Choose this plan</div>


                </div>
                
              
            
            
            
            
            <div class="divbox2">
                 <div class="divboxmain">
                <div class="divbox1a">
                    
                    <img class="photo" src="images/idea.png" /></div>
                 <div class="divbox1b">PREMIUM</div>
                <div class="divbox1c">₦80,000</div>
                <div class="divbox1ci">/year</div>
                  </div>
          
                <hr class="new1">

                <div class="divbox1d">2 users</div>
                 <div class="divbox1d">1 business locations</div>
                 <div class="divbox1d">point of sales</div>
                 <div class="divbox1d">Inventory Manager</div>
                 <div class="divbox1d">Billing and invoicing</div>
                 <div class="divbox1d">Marketing and CRM</div>
                 <div class="divbox1d">Payments solutions </div>
                 <div class="divbox1d">Customer Settings</div>
                 <div class="divbox1d">Productions</div>
                 <div class="divbox1d">HRM/Payroll</div>

                <div class="divbox1e">Choose this plan</div>
                
                
                
                  </div>







            <div class="divbox3">
                <div class="divboxmain">
                <div class="divbox1a">
                    <img class="photo" src="images/crown.png" /></div>
                 <div class="divbox1b">ULTIMATE</div>
                     <div class="divbox1cc">₦100,000</div>
                <div class="divbox1ci">/year</div>
                </div>


                 <hr class="new1">

                <div class="divbox1d">2 users</div>
                 <div class="divbox1d">1 business locations</div>
                 <div class="divbox1d">point of sales</div>
                 <div class="divbox1d">Inventory Manager</div>
                 <div class="divbox1d">Billing and invoicing</div>
                 <div class="divbox1d">Marketing and CRM</div>
                 <div class="divbox1d">Payments solutions </div>
                 <div class="divbox1d">Customer Settings</div>
                 <div class="divbox1d">Productions</div>
                 <div class="divbox1d">HRM/Payroll</div>
                <div class="divbox1d">Accounting</div>
                <div class="divbox1e">Choose this plan</div>
                


            </div>
        </div>


            <div class="boxhouse">
            
               <div class="boxone">Copyright © 2024 NoksPos</div>
           <a href="Policy.html"><div class="policy">privacy policy</div></a>
               
                 </div>


   
    </form>
</body>
</html>

new/nokstech2/Views/Register/register.cshtml
@{
    ViewData["Title"] = "Registration";
    ViewData["Css"] = "Register.css";
}

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
     <meta  name="viewport" content="width=device-width, initial-scale=1.0>" />
    <!--<link href="Register.css" rel="stylesheet" />
    <title>Registration</title>-->
</head>
<body>
    <form id="form1" runat="server">
    <div class="topdiv">
    <div class="logo">
        <div class="logobus">
                     <img class="img" src="images/logomain4.0.png" /></div>
                     <div class="newtext">NOKS</div>
                     <div class="newtext1">POS</div>
                 </div>
    </div>
        <div class="maindiv">
            <div class="div">Create Your NoksPos Account.</div>
            <asp:TextBox CssClass="textbox" ID="TextBox1" placeholder="Enter Full Name" runat="server"></asp:TextBox>
            <asp:TextBox CssClass="textbox" ID="TextBox2" placeholder="Phone Number" runat="server"></asp:TextBox>
            <asp:TextBox CssClass="textbox" ID="TextBox3" placeholder="Choose Username" runat="server"></asp:TextBox>
            <asp:TextBox CssClass="textbox" ID="TextBox4" placeholder="Enter Email Address" runat="server"></asp:TextBox>
            <asp:TextBox CssClass="textbox" ID="TextBox5" placeholder="Password" runat="server"></asp:TextBox>
            <div class="housing">
            <div class="divbox">
                <div class="divbox1">
                    <img class="image" src="images/correct.png" />
                    <div class="text">At least 8 characters</div>
                </div>
                
                 <div class="divbox1">
                     <img class="image" src="images/correct.png" />
                    <div class="text">At least 1 uppercase letter</div>
                 </div>
                 <div class="divbox1">
                     <img class="image" src="images/correct.png" />
                    <div class="text">At least 1 special character</div>
                 </div>
            </div>




              <div class="divbox2">
                <div class="divbox1">
                     <img class="image" src="images/correct.png" />
                    <div class="text">At least 1 lowercase letter</div>
                </div>
                
                 <div class="divbox1">
                      <img class="image" src="images/correct.png" />
                    <div class="text">At least 1 numerical number</div>
                 </div>
               
            </div>

            </div>

            <div class="divbox3">Register</div>
            <div class="housingbox">
            <div class="divbox4">Already Have An Account?</div>
            <a class="divbox5" href="http://noksworld-003-site22.btempurl.com/" target="_blank" rel="noopener noreferrer">Login</a>
            </div>
        </div>
    </form>
</body>
</html>

new/nokstech2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @if (ViewData["Css"] != null)
    {
        <link rel="stylesheet" href="~/css/@ViewData["Css"]" asp-append-version="true" />
    } else if (ViewData["Css"] == null)
    {
        <link href="~/css/StyleSheet.css" rel="stylesheet" asp-append-version="true" />
    }
    @if (ViewData["Extra_Css"] != null)
    {
        <link rel="stylesheet" href="~/css/@ViewData["Extra_Css"]" asp-append-version="true" />
    }
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>